/**
@Author - Vinutha
@name - AP61_Prospect_Response
@CreateDate - 05-05-2015
@Description - This is a response class to send prospect data
@Version - 1.0
@reference - NR
**/
global class AP71_Prospect_Response{
global String chromeLocalId{get;set;}
/*global Prospect__c prospect{get;set;}
global Route_Prospect__c routeProspect{get;set;}
global AP08_ErrorDetails errorDetails{get;set;}*/
//Testing GIT Commit 2

}